---
openapi: 3.0.0
info:
  title: Trail Flask REST API
  description: "An API for coursework Users, descriptions, tags, and more"
  version: 1.0.0
servers:
- url: /api
  description: base url for the API
components:
  schemas:
    userTable:
      type: object
      required:
        - userName
        - userSurname
        - userid
        - userEmail
        - userRole
        - passwordHash
      properties:
        userName:
          type: string
        userSurname:
          type: string
        userid:
          type: string
        userEmail:
          type: string
          format: email
        userDate:
          type: string
          format: date
        userRole:
          type: string
        passwordHash:
          type: string
paths:
  /users:
    get:
      summary: Get all users
      operationId: controllers.getUsers
      responses:
        "200":
          description: Successfully retrieved all users