##this is a swagger file

openapi: 3.0.0
info:
  title: "trail flask rest api"
  description: "an api for coursework Users, descriptions, tags and possibly more"
  version: "1.0.0"

  servers:
    - url: "/api"

  paths:
    /users:
      get:
        summary: "get all users"
        responses:
          "200":
            description: "successful read all users"
            
              