---
openapi: 3.0.0
info:
  title: Trail Flask REST API
  description: "An API for coursework Users, descriptions, tags, and more"
  version: 1.0.0
servers:
- url: /api
  description: base url for the API
components:
  schemas:
    userTable:
      type: object
      required:
        - userName
        - userSurname
        - userid
        - userEmail
        - userRole
        - passwordHash
      properties:
        userName:
          type: string
        userSurname:
          type: string
        userid:
          type: string
        userEmail:
          type: string
          format: email
        userDate:
          type: string
          format: date
        userRole:
          type: string
        passwordHash:
          type: string

    TrailsTable
      type: object
      required:
        - trailid
        - trailName
        - lengthInKm
        - elevationInM
        - routeType
        - TimeToComplete
        - locationoftrail
        - pets
      properties:
        trailid:
          type: int
        trailName:
          type: string
        lengthInKm:
          type: number
          formate: float
        elevationInM:
          type: number
          formate: float
        routeType:
          type: string
        TimeToComplete:
          type: integer
        locationoftrail:
          type: string
        pets:
          type: string


        
paths:
  /users:
    get:
      summary: Get all users
      operationId: controllers.getUsers
      responses:
        "200":
          description: Successfully retrieved all users

paths:
  /trails:
    get:
      summary: Get all trails
      operationId: controllers.getTrails
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TrailsTable'
    post:
      summary: add a new trail
      operationId: controllers.addTrail
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrailsTable'
      responses:
        "201":
          description: Successfully added a new trail
