---
openapi: 3.0.0
info:
  title: Trail Flask REST API
  description: "An API for coursework Users, descriptions, tags, and more"
  version: 1.0.0
servers:
- url: /api
  description: base url for the API
components:
  schemas:
    userTable:
      type: object
      required:
        - userName
        - userSurname
        - userid
        - userEmail
        - userRole
        - passwordHash
      properties:
        userName:
          type: string
        userSurname:
          type: string
        userid:
          type: string
        userEmail:
          type: string
          format: email
        userDate:
          type: string
          format: date
        userRole:
          type: string
        passwordHash:
          type: string

    Trails:
      type: object
      required:
        - trailid
        - trailName
        - routeType
        - TimeToComplete
        - locationoftrail
        - pets
      properties:
        trailid:
          type: int
        trailName:
          type: string
        routeType:
          type: string
        TimeToComplete:
          type: integer
        locationoftrail:
          type: string
        pets:
          type: string


        
paths:
  /users:
    get:
      summary: Get all users
      operationId: controllers.getUsers
      responses:
        "200":
          description: Successfully retrieved all users

  paths:
  /trails:
    get:
      summary: Get all trails
      operationId: controllers.getTrails
      responses:
        "200":
          description: Successfully retrieved all trails
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trails'
        "400":
          description: Bad request
        "500":
          description: Internal server error
    post:
      summary: add a new trail
      operationId: controllers.addTrail
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trails'
      responses:
        "201":
          description: Successfully added a new trail
    put:
      summary: update a  trail
      operationId: controllers.updateTrail
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trails'
      responses:
        "201":
          description: Successfully added updated a trail
        "400":
            description: Bad request
        "500":
            description: Internal server error
     delete:
      summary:  delete trail
      operationId: controllers.deleteTrail
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trails'
      responses:
        "201":
          description: Successfully deleted a trail
        "400":
            description: Bad request
        "500":
            description: Internal server error 
